kind: Service
apiVersion: v1
metadata:
  name:  github-actions-demo=lb
spec:
  selector:
    app:  frontend
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  3000
---
kind: Service
apiVersion: v1
metadata:
  name:  github-actions-demo-backend
spec:
  selector:
    app:  backend
  type:  ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort:  8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name:  github-actions-demo-frontend
spec:
  replicas:  1
  selector:
    matchLabels:
      app:  frontend
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      containers:
      - name:  github-actions-demo-frontend
        image:  ghcr.io/tniita/ochacafe-github-actions/oke-app-golang:latest
        ports:
        - containerPort:  3000
        resources:
          requests:
            cpu:  200m
            memory:  100Mi
          limits:
            cpu:  200m
            memory:  100Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name:  github-actions-demo-backend
spec:
  replicas:  1
  selector:
    matchLabels:
      app:  backend
  template:
    metadata:
      labels:
        app:  backend
    spec:
      containers:
      - name:  github-actions-demo-backend
        image:  ghcr.io/tniita/ochacafe-github-actions/oke-app-nextjs:latest
        ports:
        - containerPort:  8080
        resources:
          requests:
            cpu:  200m
            memory:  100Mi
          limits:
            cpu:  200m
            memory:  100Mi
