name: OKE GitHub Actions Deploy Demo

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      User: ${{ secrets.OCI_CLI_USER }}
      Tenancy: ${{ secrets.OCI_CLI_TENANCY }}
      Fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
      KeyContent: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      RegionId: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Start message
        run: echo "Welcome to OKE GitHub Actions Deploy Demo"

      - uses: actions/checkout@v3
        name: Checkout

      - name: Configure Kubectl for Oracle Container Engine for Kubernetes (OKE)
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Run Kubectl
        run: |
          kubectl apply -f k8s/demo.yaml

      - name: Finish message
        run: echo "Finished running OKE GitHub Actions Deploy Demo"
