name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-A:
    uses: tniita/ochacafe-github-actions/.github/workflows/workflow-A.yaml@v1

  call-workflow-B:
    uses: tniita/ochacafe-github-actions/.github/workflows/workflow-B.yaml@v1
