name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-A:
    uses: tniita/ochacafe-github-actions/.github/workflows/workflow-A.yaml@main

  call-workflow-B:
    uses: tniita/ochacafe-github-actions/.github/workflows/workflow-B.yaml@main
